version: "3.2"
services:
  nodejs:
    build: 
      context: .
    image: armiariyan/test-intern
    networks:
      - frontend
      - backend
    environment:
      - MYSQL_HOST=armiariyan-mysql-app
      - MYSQL_USER=armiariyan
      - MYSQL_PASS=armiariyan
      - MYSQL_DB=belajar_express
    volumes:
      - ./www/:/var/www/html/
    ports:
      - "30001:3000"
    container_name: armiariyan-nodejs-app
  mysql:
    image: mysql:5.7
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=armiariyan
      - MYSQL_PASSWORD=armiariyan 
      - MYSQL_DATABASE=belajar_express
    container_name: armiariyan-mysql-app
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.7
    depends_on:
      - mysql
    networks:
      - backend
    ports:
      - "30002:80"
    environment:
      - PMA_HOST=armiariyan-mysql-app
      - PMA_PORT= 3306
    volumes:
      - /sessions
    container_name: armiariyan-phpmyadmin-app
networks:
  frontend:
  backend: